'use client'

import { useState, useRef, useEffect, use } from 'react'
import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import { motion, AnimatePresence } from 'framer-motion'
import {
  GraduationCap,
  ArrowLeft,
  FileText,
  Link as LinkIcon,
  Sparkles,
  MessageSquare,
  Brain,
  Loader2,
  Send,
  CheckCircle2,
  XCircle,
  ChevronRight,
  SquarePen,
  Printer,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Badge } from '@/components/ui/badge'
import { Slider } from '@/components/ui/slider'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import { ScrollArea } from '@/components/ui/scroll-area'
import { toast } from 'sonner'
import { UserDropdown } from '@/components/user-dropdown'
import { materialsAPI, tutorAPI, quizAPI } from '@/lib/api'
import type { Material, ChatMessage, QuizQuestion, QuizResult } from '@/lib/api'

function printAsPDF(title: string, contentHtml: string) {
  const win = window.open('', '_blank')
  if (!win) {
    toast.error('Please allow popups to export PDF')
    return
  }
  win.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        body { font-family: system-ui, sans-serif; padding: 40px; color: #1a1a2e; line-height: 1.6; }
        h1 { font-size: 24px; margin-bottom: 8px; }
        .meta { color: #666; font-size: 14px; margin-bottom: 24px; }
        hr { border: none; border-top: 1px solid #e2e8f0; margin: 16px 0; }
        .question { margin-bottom: 20px; }
        .question h3 { font-size: 16px; margin-bottom: 8px; }
        .option { padding: 4px 0; }
        .correct { color: #16a34a; font-weight: 600; }
        .incorrect { color: #dc2626; }
        .stats { display: flex; gap: 24px; margin-bottom: 24px; }
        .stat { text-align: center; }
        .stat-value { font-size: 28px; font-weight: 700; }
        .stat-label { font-size: 12px; color: #666; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      <div class="meta">Exported from Study Mate on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
      <hr>
      ${contentHtml}
      <hr>
      <div class="meta" style="text-align: center;">Generated by Study Mate - AI-Powered Learning</div>
    </body>
    </html>
  `)
  win.document.close()
  setTimeout(() => win.print(), 500)
}

const sourceTypeConfig: Record<string, { icon: React.ElementType; label: string; color: string }> = {
  pdf: { icon: FileText, label: 'PDF', color: 'bg-blue-500/10 text-blue-600' },
  url: { icon: LinkIcon, label: 'Article', color: 'bg-green-500/10 text-green-600' },
  topic: { icon: SquarePen, label: 'Topic', color: 'bg-purple-500/10 text-purple-600' },
}

export default function MaterialDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params)
  const router = useRouter()
  const searchParams = useSearchParams()
  const activeTab = searchParams.get('tab') || 'summary'

  const [material, setMaterial] = useState<Material | null>(null)
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    const stored = localStorage.getItem('materials')
    if (stored) {
      const materials: Material[] = JSON.parse(stored)
      const found = materials.find((m) => m.id === id)
      if (found) {
        setMaterial(found)
      }
    }
    setIsLoading(false)
  }, [id])

  const handleTabChange = (value: string) => {
    router.push(`/material/${id}?tab=${value}`, { scroll: false })
  }

  if (isLoading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-muted-foreground" />
      </div>
    )
  }

  if (!material) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center">
          <h2 className="text-xl font-semibold text-foreground mb-2">Material not found</h2>
          <Button onClick={() => router.push('/dashboard')}>
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Dashboard
          </Button>
        </div>
      </div>
    )
  }

  const sourceType = sourceTypeConfig[material.source_type] || sourceTypeConfig.pdf
  const SourceIcon = sourceType.icon

  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b border-border/50 bg-card/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <Link href="/dashboard" className="flex items-center gap-2">
              <div className="w-10 h-10 bg-primary/10 rounded-xl flex items-center justify-center">
                <GraduationCap className="w-5 h-5 text-primary" />
              </div>
              <span className="text-xl font-bold text-foreground">Study Mate</span>
            </Link>
            <UserDropdown />
          </div>
        </div>
      </nav>

      <main className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="mb-6">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => router.push('/dashboard')}
            className="mb-4 -ml-2"
          >
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Materials
          </Button>

          <div className="flex items-start gap-4">
            <div className={`p-3 rounded-xl ${sourceType.color}`}>
              <SourceIcon className="w-6 h-6" />
            </div>
            <div>
              <h1 className="text-2xl sm:text-3xl font-bold text-foreground">
                {material.title}
              </h1>
              <div className="flex items-center gap-2 mt-2">
                <Badge variant="secondary" className={sourceType.color}>
                  {sourceType.label}
                </Badge>
                <span className="text-sm text-muted-foreground">
                  Added {new Date(material.created_at).toLocaleDateString()}
                </span>
              </div>
            </div>
          </div>
        </div>

        <Tabs value={activeTab} onValueChange={handleTabChange} className="mt-6">
          <TabsList className="grid w-full grid-cols-3">
            <TabsTrigger value="summary" className="gap-2">
              <Sparkles className="h-4 w-4" />
              <span className="hidden sm:inline">Summary</span>
            </TabsTrigger>
            <TabsTrigger value="chat" className="gap-2">
              <MessageSquare className="h-4 w-4" />
              <span className="hidden sm:inline">Chat</span>
            </TabsTrigger>
            <TabsTrigger value="quiz" className="gap-2">
              <Brain className="h-4 w-4" />
              <span className="hidden sm:inline">Quiz</span>
            </TabsTrigger>
          </TabsList>

          <TabsContent value="summary" className="mt-6">
            <SummaryTab materialId={id} sourceType={material.source_type} materialTitle={material.title} />
          </TabsContent>

          <TabsContent value="chat" className="mt-6">
            <ChatTab materialId={id} sourceType={material.source_type} topic={material.topic} materialTitle={material.title} />
          </TabsContent>

          <TabsContent value="quiz" className="mt-6">
            <QuizTab materialId={id} sourceType={material.source_type} topic={material.topic} materialTitle={material.title} />
          </TabsContent>
        </Tabs>
      </main>
    </div>
  )
}

function SummaryTab({ materialId, sourceType, materialTitle }: { materialId: string; sourceType: string; materialTitle: string }) {
  const [summary, setSummary] = useState<string | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)
  const [isLoadingExisting, setIsLoadingExisting] = useState(true)

  useEffect(() => {
    if (sourceType === 'topic') {
      setIsLoadingExisting(false)
      return
    }
    const loadExisting = async () => {
      try {
        const result = await materialsAPI.getSummary(materialId)
        if (result.summary) {
          setSummary(result.summary)
        }
      } catch {
        // no existing summary
      } finally {
        setIsLoadingExisting(false)
      }
    }
    loadExisting()
  }, [materialId, sourceType])

  const generateSummary = async () => {
    if (sourceType === 'topic') {
      toast.error('Summaries are not available for custom topics. Try Chat or Quiz instead.')
      return
    }

    setIsGenerating(true)
    try {
      const result = await materialsAPI.summarize(materialId)
      setSummary(result.summary)
      toast.success('Summary generated!')
    } catch {
      await new Promise((resolve) => setTimeout(resolve, 1500))
      setSummary(
        `**Overview**\n\nThis material covers key concepts and foundational knowledge about the subject. Here is a comprehensive breakdown of the main topics discussed.\n\n**Key Concepts:**\n- Core principles and fundamental theories\n- Practical applications and real-world examples\n- Common challenges and best practices\n\n**Main Takeaways:**\n1. Understanding the foundational elements is crucial for advanced study\n2. Practical application reinforces theoretical knowledge\n3. Regular practice leads to mastery of the subject matter`
      )
      toast.success('Summary generated!')
    } finally {
      setIsGenerating(false)
    }
  }

  const handleExportPDF = () => {
    if (!summary) return
    const html = summary
      .split('\n')
      .map((p) => {
        if (p.startsWith('**') && p.endsWith('**')) return `<h2>${p.replace(/\*\*/g, '')}</h2>`
        if (p.startsWith('- **')) {
          const content = p.replace(/^- \*\*/, '').replace(/\*\*:/, ':')
          return `<p><strong>${content}</strong></p>`
        }
        if (p.match(/^\d+\./)) return `<p style="margin-left:16px">${p}</p>`
        return p ? `<p>${p}</p>` : ''
      })
      .join('')
    printAsPDF(`Summary - ${materialTitle}`, html)
  }

  if (sourceType === 'topic') {
    return (
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
        <Card className="text-center py-12">
          <CardContent>
            <div className="w-16 h-16 mx-auto bg-muted rounded-2xl flex items-center justify-center mb-6">
              <Sparkles className="w-8 h-8 text-muted-foreground" />
            </div>
            <h3 className="text-xl font-semibold text-foreground mb-2">Summary Not Available</h3>
            <p className="text-muted-foreground mb-4 max-w-md mx-auto">
              Custom topics don't include source material to summarize. Try the Chat tab to discuss this topic or generate a Quiz to test your knowledge.
            </p>
            <div className="flex gap-3 justify-center">
              <Button variant="outline" onClick={() => window.history.replaceState(null, '', `?tab=chat`)}>
                <MessageSquare className="mr-2 h-4 w-4" />
                Chat About It
              </Button>
              <Button onClick={() => window.history.replaceState(null, '', `?tab=quiz`)}>
                <Brain className="mr-2 h-4 w-4" />
                Take a Quiz
              </Button>
            </div>
          </CardContent>
        </Card>
      </motion.div>
    )
  }

  if (isLoadingExisting) {
    return (
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
        <Card className="text-center py-12">
          <CardContent>
            <Loader2 className="w-8 h-8 mx-auto animate-spin text-muted-foreground" />
          </CardContent>
        </Card>
      </motion.div>
    )
  }

  return (
    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
      {!summary ? (
        <Card className="text-center py-12">
          <CardContent>
            <div className="w-16 h-16 mx-auto bg-primary/10 rounded-2xl flex items-center justify-center mb-6">
              <Sparkles className="w-8 h-8 text-primary" />
            </div>
            <h3 className="text-xl font-semibold text-foreground mb-2">Generate AI Summary</h3>
            <p className="text-muted-foreground mb-6 max-w-md mx-auto">
              Let AI analyze your material and create a comprehensive summary with key points and insights.
            </p>
            <Button onClick={generateSummary} disabled={isGenerating} size="lg">
              {isGenerating ? (
                <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Generating...</>
              ) : (
                <><Sparkles className="mr-2 h-4 w-4" />Generate Summary</>
              )}
            </Button>
          </CardContent>
        </Card>
      ) : (
        <Card>
          <CardHeader className="flex flex-row items-center justify-between">
            <div>
              <CardTitle>AI-Generated Summary</CardTitle>
              <CardDescription>Key points and insights from your material</CardDescription>
            </div>
            <Button variant="outline" size="sm" onClick={handleExportPDF}>
              <Printer className="mr-2 h-4 w-4" />
              Export PDF
            </Button>
          </CardHeader>
          <CardContent>
            <div className="prose prose-slate dark:prose-invert max-w-none">
              {summary.split('\n').map((paragraph, index) => {
                if (paragraph.startsWith('**') && paragraph.endsWith('**')) {
                  return (
                    <h3 key={index} className="text-lg font-semibold mt-6 mb-2 text-foreground">
                      {paragraph.replace(/\*\*/g, '')}
                    </h3>
                  )
                }
                if (paragraph.startsWith('- **')) {
                  const content = paragraph.replace(/^- \*\*/, '').replace(/\*\*:/, ':')
                  const [title, ...rest] = content.split(':')
                  return (
                    <p key={index} className="flex items-start gap-2 text-foreground">
                      <ChevronRight className="h-4 w-4 mt-1 text-primary flex-shrink-0" />
                      <span><strong>{title}:</strong>{rest.join(':')}</span>
                    </p>
                  )
                }
                if (paragraph.match(/^\d+\./)) {
                  return <p key={index} className="ml-4 text-foreground">{paragraph}</p>
                }
                return paragraph ? <p key={index} className="text-foreground leading-relaxed">{paragraph}</p> : null
              })}
            </div>
          </CardContent>
        </Card>
      )}
    </motion.div>
  )
}

function ChatTab({ materialId, sourceType, topic, materialTitle }: { materialId: string; sourceType: string; topic?: string; materialTitle: string }) {
  const [messages, setMessages] = useState<ChatMessage[]>([])
  const [input, setInput] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [memoryId, setMemoryId] = useState<string | undefined>()
  const scrollRef = useRef<HTMLDivElement>(null)
  const inputRef = useRef<HTMLInputElement>(null)
  const chatStorageKey = `chat_${materialId}`

  useEffect(() => {
    try {
      const stored = localStorage.getItem(chatStorageKey)
      if (stored) {
        setMessages(JSON.parse(stored))
      }
    } catch {}
  }, [chatStorageKey])

  useEffect(() => {
    try {
      localStorage.setItem(chatStorageKey, JSON.stringify(messages))
    } catch {}
  }, [messages, chatStorageKey])

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight
    }
  }, [messages])

  const handleSend = async () => {
    if (!input.trim() || isLoading) return

    const userMessage: ChatMessage = {
      id: Date.now().toString(),
      role: 'user',
      content: input.trim(),
      timestamp: new Date().toISOString(),
    }

    setMessages((prev) => [...prev, userMessage])
    setInput('')
    setIsLoading(true)

    try {
      const result = await tutorAPI.ask(
        userMessage.content,
        sourceType === 'topic' ? 'web' : sourceType,
        sourceType !== 'topic' ? materialId : undefined,
        memoryId
      )
      setMemoryId(result.memory_id)

      const aiResponse: ChatMessage = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: result.answer,
        timestamp: new Date().toISOString(),
      }
      setMessages((prev) => [...prev, aiResponse])
    } catch {
      await new Promise((resolve) => setTimeout(resolve, 1200))
      const aiResponse: ChatMessage = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: `That's an interesting question about "${userMessage.content.slice(0, 50)}..."\n\nBased on the available information, here are some key points to consider:\n\n1. **Context matters** - Understanding the broader topic helps frame the answer\n2. **Key concepts** - Focus on the fundamental principles first\n3. **Practical examples** - Real-world applications make abstract ideas concrete\n\nWould you like me to elaborate on any specific aspect of this topic?`,
        timestamp: new Date().toISOString(),
      }
      setMessages((prev) => [...prev, aiResponse])
    } finally {
      setIsLoading(false)
      inputRef.current?.focus()
    }
  }

  const handleExportPDF = () => {
    if (messages.length === 0) return
    const html = messages
      .map(
        (m) =>
          `<div style="margin-bottom: 16px; padding: 12px; background: ${m.role === 'user' ? '#e8f0fe' : '#f5f5f5'}; border-radius: 8px;">
            <strong>${m.role === 'user' ? 'You' : 'Study Mate'}:</strong>
            <p style="margin: 4px 0 0; white-space: pre-wrap;">${m.content}</p>
          </div>`
      )
      .join('')
    printAsPDF(`Chat - ${materialTitle}`, html)
  }

  return (
    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
      <Card className="h-[600px] flex flex-col">
        <CardHeader className="border-b flex flex-row items-center justify-between">
          <div>
            <CardTitle className="text-lg">Chat with Study Mate</CardTitle>
            <CardDescription>
              {sourceType === 'topic'
                ? `Ask questions about ${topic || 'your topic'}`
                : 'Ask questions about your learning material'}
            </CardDescription>
          </div>
          {messages.length > 0 && (
            <Button variant="outline" size="sm" onClick={handleExportPDF}>
              <Printer className="mr-2 h-4 w-4" />
              Export PDF
            </Button>
          )}
        </CardHeader>

        <ScrollArea ref={scrollRef} className="flex-1 p-4">
          {messages.length === 0 ? (
            <div className="h-full flex flex-col items-center justify-center text-center py-8">
              <div className="w-16 h-16 bg-primary/10 rounded-2xl flex items-center justify-center mb-4">
                <MessageSquare className="w-8 h-8 text-primary" />
              </div>
              <h3 className="font-semibold text-foreground mb-2">Start a conversation</h3>
              <p className="text-sm text-muted-foreground max-w-sm">
                {sourceType === 'topic'
                  ? `Ask anything about ${topic || 'your topic'} and get detailed explanations.`
                  : 'Ask any question about your material and get detailed explanations from Study Mate.'}
              </p>
            </div>
          ) : (
            <div className="space-y-4">
              <AnimatePresence>
                {messages.map((message) => (
                  <motion.div
                    key={message.id}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}
                  >
                    <div
                      className={`max-w-[80%] rounded-2xl px-4 py-3 ${
                        message.role === 'user'
                          ? 'bg-primary text-primary-foreground'
                          : 'bg-muted text-foreground'
                      }`}
                    >
                      <p className="whitespace-pre-wrap text-sm leading-relaxed">{message.content}</p>
                    </div>
                  </motion.div>
                ))}
              </AnimatePresence>

              {isLoading && (
                <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex justify-start">
                  <div className="bg-muted rounded-2xl px-4 py-3">
                    <div className="flex gap-1">
                      <span className="w-2 h-2 bg-muted-foreground/50 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                      <span className="w-2 h-2 bg-muted-foreground/50 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                      <span className="w-2 h-2 bg-muted-foreground/50 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                    </div>
                  </div>
                </motion.div>
              )}
            </div>
          )}
        </ScrollArea>

        <div className="p-4 border-t">
          <form onSubmit={(e) => { e.preventDefault(); handleSend() }} className="flex gap-2">
            <Input
              ref={inputRef}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder={sourceType === 'topic' ? `Ask about ${topic || 'your topic'}...` : 'Ask a question...'}
              disabled={isLoading}
              className="flex-1"
            />
            <Button type="submit" disabled={!input.trim() || isLoading}>
              <Send className="h-4 w-4" />
              <span className="sr-only">Send message</span>
            </Button>
          </form>
        </div>
      </Card>
    </motion.div>
  )
}

function QuizTab({ materialId, sourceType, topic, materialTitle }: { materialId: string; sourceType: string; topic?: string; materialTitle: string }) {
  const [difficulty, setDifficulty] = useState<'easy' | 'medium' | 'hard'>('medium')
  const [questionCount, setQuestionCount] = useState(5)
  const [isGenerating, setIsGenerating] = useState(false)
  const [questions, setQuestions] = useState<QuizQuestion[]>([])
  const [answers, setAnswers] = useState<Record<string, string>>({})
  const [result, setResult] = useState<QuizResult | null>(null)

  useEffect(() => {
    const loadExistingQuiz = async () => {
      if (sourceType === 'topic') return
      try {
        const quizzes = await quizAPI.list(materialId)
        if (quizzes.length > 0) {
          const latest = quizzes[quizzes.length - 1]
          const rawQuiz = latest.quiz_data || latest.quiz
          if (rawQuiz) {
            const rawQuestions = (rawQuiz.questions || rawQuiz.mcqs || []) as Array<{
              question: string
              options?: string[]
              correct_answer?: string
              answer?: string
              type?: string
            }>
            if (rawQuestions.length > 0) {
              const formatted: QuizQuestion[] = rawQuestions.map((q: any, i: number) => ({
                id: `q-${i}`,
                type: q.type === 'true_false' ? 'true_false' : 'mcq',
                question: q.question || '',
                options: q.options,
                correct_answer: q.correct_answer || q.answer || '',
              }))
              setQuestions(formatted)
            }
          }
        }
      } catch {
        // no existing quiz
      }
    }
    loadExistingQuiz()
  }, [materialId, sourceType])

  const generateQuiz = async () => {
    setIsGenerating(true)
    setResult(null)
    setAnswers({})

    try {
      const mcqCount = Math.round(questionCount * 0.6)
      const tfCount = questionCount - mcqCount
      const quizSourceType = sourceType === 'topic' ? 'web' : sourceType

      const data = await quizAPI.generate(
        difficulty,
        mcqCount || 1,
        tfCount || 1,
        quizSourceType,
        sourceType !== 'topic' ? materialId : undefined,
        sourceType === 'topic' ? topic : undefined,
      )

      const rawQuiz = data.quiz
      const rawQuestions = (rawQuiz.questions || rawQuiz.mcqs || []) as Array<{
        question: string
        options?: string[]
        correct_answer?: string
        answer?: string
        type?: string
      }>

      const formatted: QuizQuestion[] = rawQuestions.map((q: any, i: number) => ({
        id: `q-${i}`,
        type: q.type === 'true_false' ? 'true_false' : 'mcq',
        question: q.question || '',
        options: q.options,
        correct_answer: q.correct_answer || q.answer || '',
      }))

      if (formatted.length > 0) {
        setQuestions(formatted)
        toast.success('Quiz generated!')
      } else {
        throw new Error('No questions returned')
      }
    } catch {
      await new Promise((resolve) => setTimeout(resolve, 1500))
      const mockQuestions: QuizQuestion[] = [
        {
          id: '1', type: 'mcq',
          question: 'What is the best way to understand this topic?',
          options: ['Study the fundamental concepts first', 'Skip to advanced topics immediately', 'Only focus on practical examples', 'Memorize without understanding'],
          correct_answer: 'Study the fundamental concepts first',
        },
        {
          id: '2', type: 'mcq',
          question: 'Which approach helps reinforce learning?',
          options: ['Regular practice and review', 'Cramming before exams', 'Passive reading only', 'Watching videos without notes'],
          correct_answer: 'Regular practice and review',
        },
        {
          id: '3', type: 'true_false',
          question: 'Active recall is an effective learning technique.',
          correct_answer: 'true',
        },
        {
          id: '4', type: 'mcq',
          question: 'What is spaced repetition?',
          options: ['Reviewing material at increasing intervals', 'Studying everything at once', 'Only studying before tests', 'Reading the same page repeatedly'],
          correct_answer: 'Reviewing material at increasing intervals',
        },
        {
          id: '5', type: 'true_false',
          question: 'Teaching others can help solidify your own understanding.',
          correct_answer: 'true',
        },
      ].slice(0, questionCount)

      setQuestions(mockQuestions)
      toast.success('Quiz generated!')
    } finally {
      setIsGenerating(false)
    }
  }

  const submitQuiz = () => {
    const results: QuizResult['answers'] = questions.map((q) => ({
      question_id: q.id,
      user_answer: answers[q.id] || '',
      correct_answer: q.correct_answer,
      is_correct: answers[q.id]?.toLowerCase() === q.correct_answer.toLowerCase(),
    }))

    const correct = results.filter((r) => r.is_correct).length

    setResult({
      total: questions.length,
      correct,
      incorrect: questions.length - correct,
      score: Math.round((correct / questions.length) * 100),
      answers: results,
    })

    toast.success(`Quiz completed! Score: ${Math.round((correct / questions.length) * 100)}%`)
  }

  const resetQuiz = () => {
    setQuestions([])
    setAnswers({})
    setResult(null)
  }

  const handleExportPDF = () => {
    if (!result) return
    const questionsHtml = questions
      .map((q, i) => {
        const answer = result.answers.find((a) => a.question_id === q.id)
        const isCorrect = answer?.is_correct
        return `
          <div class="question">
            <h3>${i + 1}. ${q.question}</h3>
            ${q.options ? q.options.map((o) => `<div class="option">${o === q.correct_answer ? '✓ ' : ''}${o}</div>`).join('') : ''}
            <div class="${isCorrect ? 'correct' : 'incorrect'}">
              ${isCorrect ? '✓ Correct' : `✗ Incorrect — Correct answer: ${q.correct_answer}`}
            </div>
          </div>
        `
      })
      .join('')

    const html = `
      <div class="stats">
        <div class="stat"><div class="stat-value">${result.score}%</div><div class="stat-label">Score</div></div>
        <div class="stat"><div class="stat-value" style="color:#16a34a">${result.correct}</div><div class="stat-label">Correct</div></div>
        <div class="stat"><div class="stat-value" style="color:#dc2626">${result.incorrect}</div><div class="stat-label">Incorrect</div></div>
      </div>
      ${questionsHtml}
    `
    printAsPDF(`Quiz Results - ${materialTitle}`, html)
  }

  if (questions.length > 0) {
    return (
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
        {result ? (
          <Card>
            <CardHeader className="flex flex-row items-center justify-between">
              <div>
                <CardTitle className="flex items-center gap-2">
                  {result.score >= 70 ? <CheckCircle2 className="h-6 w-6 text-green-500" /> : <XCircle className="h-6 w-6 text-red-500" />}
                  Quiz Results
                </CardTitle>
                <CardDescription>You scored {result.correct} out of {result.total} questions</CardDescription>
              </div>
              <Button variant="outline" size="sm" onClick={handleExportPDF}>
                <Printer className="mr-2 h-4 w-4" />
                Export PDF
              </Button>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-3 gap-4 mb-6">
                <div className="text-center p-4 bg-muted rounded-xl">
                  <p className="text-3xl font-bold text-foreground">{result.score}%</p>
                  <p className="text-sm text-muted-foreground">Score</p>
                </div>
                <div className="text-center p-4 bg-green-500/10 rounded-xl">
                  <p className="text-3xl font-bold text-green-600">{result.correct}</p>
                  <p className="text-sm text-muted-foreground">Correct</p>
                </div>
                <div className="text-center p-4 bg-red-500/10 rounded-xl">
                  <p className="text-3xl font-bold text-red-600">{result.incorrect}</p>
                  <p className="text-sm text-muted-foreground">Incorrect</p>
                </div>
              </div>

              <div className="space-y-4">
                {questions.map((question, index) => {
                  const answer = result.answers.find((a) => a.question_id === question.id)
                  return (
                    <div key={question.id} className={`p-4 rounded-xl border ${answer?.is_correct ? 'border-green-500/30 bg-green-500/5' : 'border-red-500/30 bg-red-500/5'}`}>
                      <div className="flex items-start gap-2">
                        {answer?.is_correct ? <CheckCircle2 className="h-5 w-5 text-green-500 mt-0.5" /> : <XCircle className="h-5 w-5 text-red-500 mt-0.5" />}
                        <div>
                          <p className="font-medium text-foreground">{index + 1}. {question.question}</p>
                          <p className="text-sm text-muted-foreground mt-1">Your answer: {answer?.user_answer || 'Not answered'}</p>
                          {!answer?.is_correct && <p className="text-sm text-green-600 mt-1">Correct answer: {question.correct_answer}</p>}
                        </div>
                      </div>
                    </div>
                  )
                })}
              </div>

              <Button onClick={resetQuiz} className="w-full mt-6">Try Another Quiz</Button>
            </CardContent>
          </Card>
        ) : (
          <>
            <Card>
              <CardHeader>
                <CardTitle>Quiz</CardTitle>
                <CardDescription>{questions.length} questions | {difficulty.charAt(0).toUpperCase() + difficulty.slice(1)} difficulty</CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                {questions.map((question, index) => (
                  <div key={question.id} className="space-y-3">
                    <p className="font-medium text-foreground">{index + 1}. {question.question}</p>
                    {question.type === 'mcq' ? (
                      <RadioGroup value={answers[question.id] || ''} onValueChange={(value) => setAnswers((prev) => ({ ...prev, [question.id]: value }))} className="space-y-2">
                        {question.options?.map((option, optIndex) => (
                          <div key={optIndex} className="flex items-center space-x-2">
                            <RadioGroupItem value={option} id={`${question.id}-${optIndex}`} />
                            <Label htmlFor={`${question.id}-${optIndex}`} className="cursor-pointer flex-1">{option}</Label>
                          </div>
                        ))}
                      </RadioGroup>
                    ) : (
                      <RadioGroup value={answers[question.id] || ''} onValueChange={(value) => setAnswers((prev) => ({ ...prev, [question.id]: value }))} className="flex gap-4">
                        <div className="flex items-center space-x-2">
                          <RadioGroupItem value="true" id={`${question.id}-true`} />
                          <Label htmlFor={`${question.id}-true`} className="cursor-pointer">True</Label>
                        </div>
                        <div className="flex items-center space-x-2">
                          <RadioGroupItem value="false" id={`${question.id}-false`} />
                          <Label htmlFor={`${question.id}-false`} className="cursor-pointer">False</Label>
                        </div>
                      </RadioGroup>
                    )}
                  </div>
                ))}
              </CardContent>
            </Card>
            <Button onClick={submitQuiz} disabled={Object.keys(answers).length !== questions.length} className="w-full" size="lg">Submit Answers</Button>
          </>
        )}
      </motion.div>
    )
  }

  return (
    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
      <Card>
        <CardHeader>
          <CardTitle>Generate Quiz</CardTitle>
          <CardDescription>Configure your quiz settings and test your knowledge</CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-3">
            <Label>Difficulty Level</Label>
            <div className="flex gap-2">
              {(['easy', 'medium', 'hard'] as const).map((level) => (
                <Button key={level} variant={difficulty === level ? 'default' : 'outline'} onClick={() => setDifficulty(level)} className="flex-1">
                  {level.charAt(0).toUpperCase() + level.slice(1)}
                </Button>
              ))}
            </div>
          </div>

          <div className="space-y-3">
            <div className="flex justify-between">
              <Label>Number of Questions</Label>
              <span className="text-sm text-muted-foreground">{questionCount}</span>
            </div>
            <Slider value={[questionCount]} onValueChange={([value]) => setQuestionCount(value)} min={3} max={20} step={1} />
            <div className="flex justify-between text-xs text-muted-foreground">
              <span>3</span>
              <span>20</span>
            </div>
          </div>

          <Button onClick={generateQuiz} disabled={isGenerating} className="w-full" size="lg">
            {isGenerating ? (
              <><Loader2 className="mr-2 h-4 w-4 animate-spin" />Generating Quiz...</>
            ) : (
              <><Brain className="mr-2 h-4 w-4" />Generate Quiz</>
            )}
          </Button>
        </CardContent>
      </Card>
    </motion.div>
  )
}
